<?php
/**
 * Generated by framework installer - Sat, 17 Oct 2015 14:33:24 +0100
*/
    class Config
    {
	const BASEDNAME	= '';
	const DBHOST	= 'localhost';
	const DB	= 'csc3123';
	const DBUSER	= 'csc3123';
	const DBPW	= 'csc3123';
	const SITENAME	= 'csc3123';
	const SITEURL	= 'http://example.com/';
	const SITENOREPLY	= 'g.i.gregory@ncl.ac.uk';
	const SYSADMIN	= 'g.i.gregory@ncl.ac.uk';
    }
?>